In [3]:
print("hello")

hello


In [19]:
%%time

import numpy as np
a = np.arange(6)
b = np.arange(1,10001)
c = np.arange(10001,20001)
d = np.zeros_like(b) # 같은 shape로 초기화 할 때 사용 가능
for i in range(10000):
    d[i] = b[i] + c[i]


Wall time: 3.99 ms


In [20]:
d

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [18]:
%%time

d = b + c

Wall time: 0 ns


In [21]:
d

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [22]:
np.exp(1)

2.718281828459045

In [23]:
np.exp(2)

7.38905609893065

In [25]:
d*2

array([20004, 20008, 20012, ..., 59992, 59996, 60000])

In [27]:
x = np.array([4,5,6,7])
x.argmin() # 최소값의 index return해

0

In [28]:
x.argmax() # 최댓값의 index return

3

In [29]:
print(x.argmin(), x.argmax()) # 같이 출력할 때는 프린트로 찍어줘야 함

0 3


In [30]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
x.sum()

21

In [33]:
x.sum(axis=0) # row의 합이 구해짐

array([ 9, 12])

In [35]:
tmp = x.sum(axis=1) # col의 합이 구해짐

In [41]:
tmp.shape

(3,)

In [46]:
x = np.array([[11,2],[23,14],[5,26]])
print(np.sort(x)) # 행단위로(행 내에서) 오름차순 정렬
print("*"*20) 
print(np.sort(x,axis=0)) # 열단위로 오름차순 정렬

[[ 2 11]
 [14 23]
 [ 5 26]]
********************
[[ 5  2]
 [11 14]
 [23 26]]


In [47]:
x

array([[11,  2],
       [23, 14],
       [ 5, 26]])

In [48]:
x = np.array([40,30,10,20])
np.argsort(x) # 오름차순 순서로 정렬 했을 때 정렬 전 index의 위치를 출력

array([2, 3, 1, 0], dtype=int64)

In [ ]:
# IQR
# 박스플롯에서 Q3 - Q1 뺀 값!