In [33]:
def forward(x,y):
    out = x*y
    return out

In [34]:
apple = 100
apple_num = 2
tax = 1.1

In [35]:
apple_price = forward(apple, apple_num)
price = forward(apple_price, tax)
print(price)

220.00000000000003


In [36]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    def forward(self,x,y):
        self.x = x
        self.y = y
        out = x*y
        return out
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx, dy

In [37]:
apple_price = forward(apple, apple_num)
price = forward(apple_price, tax)
print(int(price))

220


In [38]:
mal = MulLayer()
mtl = MulLayer()

In [39]:
apple_price = mal.forward(apple, apple_num)
price = mtl.forward(apple_price, tax)
print(int(price))

220


In [40]:
print(mal.x, mal.y)

100 2


In [41]:
print(mtl.x, mtl.y)

200 1.1


In [45]:
# backprop
dprice = 1
dapple_price, dtax = mtl.backward(dprice)
dapple, dapple_num = mal.backward(dapple_price)
print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


In [46]:
# 상수형(Constant)
import tensorflow as tf

In [60]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
d = a*b+c
# 만약
# a,b,c는 사실 'Node'라고 해야 함 : constant : 항등함수처럼 데이터를 가지고만 있어도 'Node'
# 변수는 tf.Variable

In [61]:
a

<tf.Tensor 'Const_10:0' shape=(1,) dtype=float32>

In [62]:
# 세션을 생성해서 그래프 실행
# 세션 : 그래프를 실행시켜주는 일종의 runner
sess = tf.Session()
# run에게 변수로 '실행시킬 노드'를 넣어주면 된다
sess.run(a)
print(sess.run(d))

[52.]


In [65]:
node = tf.constant([5.]) # 이렇게하면 float이 됨 # dtype를 명시하는게 더 직관적으로 좋음
print(sess.run(node))

[5.]


In [68]:
# placeholder
x = tf.placeholder(dtype=tf.float32)
y = x*2
x_data = [1,2,3]
# 이 위까지 그래프만 만든 것
# 피딩 : 학습용 데이터를 전달하는 행위(그래프를 실행하는 시점)
sess.run(y,feed_dict={x:x_data})

array([2., 4., 6.], dtype=float32)

In [71]:
# 변수(Variable) : 훈련(Training)과정에서 변화하는 
# w와 b
# hf = w*x + b
# hf = 0.5x + 2

In [78]:
x_data = [1,2,3]
x = tf.placeholder(dtype=tf.float32)
# back-prop 하며 가중치 갱신해야 함 : W는 Variable
w = tf.Variable([2.])
yhat = w*x

sess = tf.Session()
# 변수를 사용하려면 변수는 초기화 해줘야함
init = tf.global_variables_initializer()
sess.run(init)
sess.run(yhat, feed_dict={x:x_data})

array([2., 4., 6.], dtype=float32)

In [80]:
# tf.matmul <= np.dot과 같은 역할!
x_data = [[1,2,3]]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([[2.],[2.],[2.]])
y = tf.matmul(x,w)
sess = tf.Session()
# 변수를 사용하려면 변수는 초기화 해줘야함
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[12.]], dtype=float32)

In [81]:
x_data = [[1,2,3]]
x = tf.placeholder(dtype=tf.float32)
# w = tf.Variable([[2.],[2.],[2.]])
w = tf.transpose(tf.Variable([[2.,2.,2.]])) # 이런식으로 transpose 됨
y = tf.matmul(x,w)
sess = tf.Session()
# 변수를 사용하려면 변수는 초기화 해줘야함
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[12.]], dtype=float32)

In [82]:
x = tf.Variable([[1,2,3]])
w = tf.transpose(tf.constant([[2,2,2]]))
y = tf.matmul(x,w)
sess = tf.Session()
# 변수를 사용하려면 변수는 초기화 해줘야함
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[12]])

In [83]:
x_data = [[1,2,3],[1,2,3],[2,3,4]]
x = tf.placeholder(dtype=tf.float32)
# w = tf.Variable([[2.],[2.],[2.]])
w = tf.transpose(tf.Variable([[2.,2.,2.]])) # 이런식으로 transpose 됨
y = tf.matmul(x,w)
sess = tf.Session()
# 변수를 사용하려면 변수는 초기화 해줘야함
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[12.],
       [12.],
       [18.]], dtype=float32)

In [85]:
# None : 아직 결정되지 않은 상태!
x_data = [[1,2,3],[1,2,3],[2,3,4]]
x = tf.placeholder(dtype = tf.float32, shape=[None,3]) 
# row수는 data수이므로 달라지자나 => 미정 : None
w = tf.transpose(tf.constant([[2.,2.,2.]]))
y = tf.matmul(x,w) # 3*3, 3*1 => 3*1
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[12.],
       [12.],
       [18.]], dtype=float32)

In [90]:
x_data = [[1,1,1],[2,2,2]]
x = tf.placeholder(dtype=tf.float32, shape=[None,3])
w = tf.Variable([[2],[2],[2]], dtype=tf.float32)
b = tf.Variable([4], dtype=tf.float32) # b 브로드캐스팅
y = tf.matmul(x,w) + b
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:x_data})

array([[10.],
       [16.]], dtype=float32)

In [100]:
class CalcLayer:
    def __init__(self):
        self.x = None
        self.y = None
    def forwardAdd(self,x,y):
        self.x = x
        self.y = y
        out = self.x + self.y
        return out
    def forwardMul(self,x,y):
        self.x = x
        self.y = y
        out = self.x * self.y
        return out
    def backwardMul(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx, dy
    def backwardAdd(self,dout):
        dx = dout
        dy = dout
        return dx, dy
    
apple = 100
appleNum = 2
orange = 150
orangeNum = 3
tax = 1.1
# price출력 (100*2+150*3)*1.1
# dapple / dappleNum / dorange / dorangeNum / dtax

apl = CalcLayer()
orl = CalcLayer()
addl = CalcLayer()
txl = CalcLayer()

appleprice = apl.forwardMul(apple,appleNum)
orangeprice = orl.forwardMul(orange,orangeNum)
addprice = addl.forwardAdd(appleprice,orangeprice)
totprice = txl.forwardMul(addprice,tax)

print(totprice)

715.0000000000001


In [106]:
daddprice, dtax = txl.backwardMul(1)

In [107]:
dtax, daddprice

(650, 1.1)

In [108]:
dappleprice, dorangeprice = addl.backwardAdd(daddprice)
print(dappleprice, dorangeprice)

1.1 1.1


In [109]:
dapple, dappleNum = apl.backwardMul(dappleprice)
print(dapple, dappleNum)

2.2 110.00000000000001


In [114]:
dorange, dorangeNum = orl.backwardMul(dorangeprice)
print(dorange, dorangeNum)

3.3000000000000003 165.0


In [115]:
print(totprice, dapple, dappleNum, dorange, dorangeNum, dtax)

715.0000000000001 2.2 110.00000000000001 3.3000000000000003 165.0 650


In [111]:
# 2.구구단의 특정 단을 출력하는 함수 작성(placeholder사용)

In [113]:
import numpy as np
num = [[3]]
x = tf.placeholder(dtype=tf.int32, shape=[None,1])
w = tf.Variable(np.arange(1,10))
y = x * w
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
sess.run(y, feed_dict={x:num})

array([[ 3,  6,  9, 12, 15, 18, 21, 24, 27]])