In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [2]:
# step function
# x>0 이면 1 반환
# x<0 이면, 0을 반환하는 활성함수

In [3]:
def step_function(x):
    if x>0:
        return 1
    else:
        return 0
step_function(10)

1

In [5]:
# sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

y = np.arange(-5.0, 5.0, 0.1)
y1 = sigmoid(y)
y1

array([0.00669285, 0.00739154, 0.00816257, 0.0090133 , 0.0099518 ,
       0.01098694, 0.01212843, 0.01338692, 0.01477403, 0.0163025 ,
       0.01798621, 0.01984031, 0.02188127, 0.02412702, 0.02659699,
       0.02931223, 0.03229546, 0.03557119, 0.03916572, 0.04310725,
       0.04742587, 0.05215356, 0.05732418, 0.06297336, 0.06913842,
       0.07585818, 0.0831727 , 0.09112296, 0.09975049, 0.10909682,
       0.11920292, 0.13010847, 0.14185106, 0.15446527, 0.16798161,
       0.18242552, 0.19781611, 0.21416502, 0.23147522, 0.24973989,
       0.26894142, 0.2890505 , 0.31002552, 0.33181223, 0.35434369,
       0.37754067, 0.40131234, 0.42555748, 0.450166  , 0.47502081,
       0.5       , 0.52497919, 0.549834  , 0.57444252, 0.59868766,
       0.62245933, 0.64565631, 0.66818777, 0.68997448, 0.7109495 ,
       0.73105858, 0.75026011, 0.76852478, 0.78583498, 0.80218389,
       0.81757448, 0.83201839, 0.84553473, 0.85814894, 0.86989153,
       0.88079708, 0.89090318, 0.90024951, 0.90887704, 0.91682

In [6]:
def relu(x):
    return np.maximum(0,x)

relu(y)

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1,
       0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4,
       1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7,
       2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ,
       4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [8]:
A = np.array([[1,2,3],[3,4,5]]) #2x3
B = np.array([[5,6],[3,4],[1,2]]) #3x2
np.dot(A,B) #2x2
# 아시다시피 내적은 shape이 맞아야 가능합니다

array([[14, 20],
       [32, 44]])

In [33]:
# hidden layer가 1개인 간단한 신경망

X = np.array([[1],[2]])
W = np.array([[1,2],[3,4],[5,6]])
Y = np.dot(W,X)

In [34]:
print(W.shape, X.shape)

(3, 2) (2, 1)


In [35]:
Y

array([[ 5],
       [11],
       [17]])

In [36]:
X = np.array([[1,2]])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)

In [37]:
print(X.shape, W.shape)

(1, 2) (2, 3)


In [38]:
Y

array([[ 5, 11, 17]])

# Forward - Propagation!

In [39]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
A1 = np.dot(X,W1) + B1

In [40]:
A1

array([0.3, 0.7, 1.1])

In [41]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [42]:
W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]]) # 3x2
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [43]:
A2 = np.dot(Z1, W2) + B2

In [44]:
A2

array([0.51615984, 1.21402696])

In [45]:
Z2 = sigmoid(A2)

In [46]:
Z2

array([0.62624937, 0.7710107 ])

In [47]:
W3 = np.array([[0.1, 0.3],[0.2, 0.4]])
B3 = np.array([0.1, 0.2])
Z3 = sigmoid(np.dot(Z2, W3) + B3)
Z3

array([0.57855079, 0.66736228])

# Softmax 함수

In [48]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [51]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [52]:
y = exp_a / sum_exp_a

In [53]:
y

array([0.01821127, 0.24519181, 0.73659691])

# MNIST 분석

In [56]:
import tensorflow as tf

sess = tf.Session()
hi = tf.constant('hi')
print(sess.run(hi))
print(str(sess.run(hi), encoding='utf-8'))
# 자세한건 내일

b'hi'
hi


In [ ]:
# 문장 유사도
# ex : 가나다라, 가마바라 : 두 단어 사아의 편집거리가 얼마인가?
# 편