In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import matplotlib as mpl
from sklearn.decomposition import PCA

In [30]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [31]:
xy.shape # (8,5)

(8, 5)

In [5]:
xy[:,0:-1]

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02]])

In [32]:
xdata = xy[:,0:-1]
xdata.shape
ydata = xy[:,[-1]]

In [34]:
def MyScaler(data): # minmaxscaler : 우리는 열 단위로 scaling해야함
    de = np.max(data,axis=0) - np.min(data,axis=0)
    num = data - np.min(data,axis=0)
    return num/de

xdata = MyScaler(xdata)
print(xdata)

[[1.         1.         0.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783]
 [0.54412549 0.50274824 0.57608696 0.60646801]
 [0.33890353 0.31368023 0.10869565 0.45989134]
 [0.51436    0.4258239  0.30434783 0.58504805]
 [0.49556179 0.4258239  0.31521739 0.48131134]
 [0.11436064 0.         0.20652174 0.22007776]
 [0.         0.07747099 0.5326087  0.        ]]


In [35]:
xdata.shape

(8, 4)

In [36]:
ydata.shape

(8, 1)

In [37]:
x = tf.placeholder(tf.float32, shape=[None,4])
y = tf.placeholder(tf.float32, shape=[None,1])
w = tf.Variable(tf.random_normal([4,1]))
b = tf.Variable(tf.random_uniform([1]))

In [38]:
hf = tf.matmul(x,w) + b
cost = tf.reduce_mean(tf.square(hf-y))

In [39]:
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [40]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    for step in range(101):
        cv, hv, _ = sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
        print(step, "cost:", cv, "hf:", hv)

0 cost: 673882.0 hf: [[-2.680429  ]
 [ 0.11222476]
 [-0.02307516]
 [-0.24697673]
 [-0.29400027]
 [-0.2690459 ]
 [ 0.90570927]
 [ 1.3482906 ]]
1 cost: 625954.9 hf: [[36.924522]
 [39.237785]
 [32.837963]
 [25.543995]
 [29.913795]
 [28.991325]
 [21.337702]
 [21.644001]]
2 cost: 581608.06 hf: [[74.98391 ]
 [76.85808 ]
 [64.44255 ]
 [50.359306]
 [58.96869 ]
 [57.137375]
 [41.016273]
 [41.197212]]
3 cost: 540573.1 hf: [[111.556946]
 [113.03067 ]
 [ 94.838715]
 [ 74.23623 ]
 [ 86.914764]
 [ 84.2117  ]
 [ 59.970154]
 [ 60.0362  ]]
4 cost: 502601.88 hf: [[146.70055 ]
 [147.81091 ]
 [124.07266 ]
 [ 97.21063 ]
 [113.794395]
 [110.25526 ]
 [ 78.22697 ]
 [ 78.18817 ]]
5 cost: 467464.5 hf: [[180.4695  ]
 [181.25204 ]
 [152.18881 ]
 [119.31698 ]
 [139.64838 ]
 [135.30743 ]
 [ 95.813286]
 [ 95.67926 ]]
6 cost: 434948.5 hf: [[212.91644 ]
 [213.40527 ]
 [179.22989 ]
 [140.58844 ]
 [164.51587 ]
 [159.40616 ]
 [112.754654]
 [112.534645]]
7 cost: 404857.44 hf: [[244.09204]
 [244.31985]
 [205.237  ]
 [161.0

# Softmax

In [41]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
#y값은 one hot 인코딩 방식으로 초기화 함...(a,b,c)중 하나를 hot하게 함...
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0

In [42]:
num_classes = 3

x = tf.placeholder("float", [None,4])
y = tf.placeholder("float", [None,num_classes])
w = tf.Variable(tf.random_normal([4,num_classes]))
b = tf.Variable(tf.random_uniform([num_classes]))

In [43]:
hf = tf.nn.softmax(tf.matmul(x,w) + b) 
# softmax함수를 쓰자! : 이렇게 하면 확률로 return됨
# reduce_sum axis=1을 주면 행별로 더함!
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hf), axis=1))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [49]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train,feed_dict={x:x_data,y:y_data})
        if step%200==0:
            print(step, sess.run(cost, feed_dict={x:x_data,y:y_data}))
            print("="*50)
    res = sess.run(hf,feed_dict={x:np.array([1,11,7,9]).reshape(1,4)})
    print(res)
    print(sess.run(tf.argmax(res, axis=1))) 
    # axis=1 기준으로 찾아다니면서 값이 가장 큰 놈으로 출력
    print("="*50)
    res2 = sess.run(hf,feed_dict={x:np.array([1,11,7,9,1,3,4,3,1,1,0,1]).reshape(-1,4)})
    print(sess.run(tf.argmax(res2, axis=1))) 

0 6.889047
200 0.9091104
400 0.6618951
600 0.58414507
800 0.5448745
1000 0.518218
1200 0.4977128
1400 0.4809096
1600 0.466586
1800 0.45403522
2000 0.44281203
[[0.5316965  0.4674371  0.00086634]]
[0]
[0 0 2]


In [50]:
xy = np.loadtxt('731data/zoo.csv', delimiter=',', dtype=np.float32)
xy.shape

(101, 17)

In [51]:
xy

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 6.],
       [0., 1., 1., ..., 0., 0., 1.]], dtype=float32)

In [53]:
xdata = xy[:,0:-1]
ydata = xy[:,[-1]]

In [54]:
xdata.shape

(101, 16)

In [55]:
ydata.shape

(101, 1)

In [101]:
x = tf.placeholder(tf.float32, [None,16])
y = tf.placeholder(tf.int32, [None,1])
y_one_hot = tf.one_hot(y,7) # 3(y) => 0001000(y_one_hot)
# tf.one_hot에 들어가는 y는 int형이어야 함!
print("one_hot", y_one_hot)
y_one_hot = tf.reshape(y_one_hot, [-1,7])
print("reshaped_one_hot", y_one_hot)
# one_hot 함수를 사용하면 차원이 하나 증가됨! : 주의할 점 : reshape해줘야겠다
# [[0], [3], ..., [5]] => [None,1] => [[[1000000]], ... ,[[0000010]]] => [None,1,7]
# 우리가 원하는 모습은 이런게 아님!
# reshpae하면 => tf.shape(y_one_hot, [-1,7]) 코딩하면 [None,7]로 reshape됨

# 0~6 : 7가지의 동물 => 분류기 7개
# w1x1 + w2x2 + ... + w7x7 => 0번 종류의 동물에 대한 확률
# ...
# w1x1 + w2x2 + ... + w7x7 => 6번 종류의 동물에 대한 확률
# 총 7개의 분류기가 만들어짐!

one_hot Tensor("one_hot_8:0", shape=(?, 1, 7), dtype=float32)
reshaped_one_hot Tensor("Reshape_6:0", shape=(?, 7), dtype=float32)


In [102]:
w = tf.Variable(tf.random_normal([16,7]))
b = tf.Variable(tf.random_normal([7]))
# x : [None, 16], w : [16,7]
logit = tf.matmul(x,w) + b
hf = tf.nn.softmax(logit)
cost_ = tf.nn.softmax_cross_entropy_with_logits(logits=logit, labels=y_one_hot)
# 요놈이 reduce_mean은 안해줌
cost = tf.reduce_mean(cost_)
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [103]:
prediction = tf.argmax(hf,1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot,1))
# correct_prediction = tf.equal(prediction, tf.cast(y,tf.int64))
# 둘 다 됨
# 이거 뒤에꺼 그냥 y주면 안됨?
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [104]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x:xdata, y:ydata})
        if step%1000==0:
            cv, acc = sess.run([cost, accuracy], feed_dict={x:xdata,y:ydata})
            print("step: ",step, "cv: ",cv, "acc: ",acc)
# 전체 데이터로 트레이닝 수행하여 모델 생서
# 모델에 전체 데이터를 집어넣어서 정확도 출력
# 데이터를 분할하지 않았음
    pred = sess.run(prediction, feed_dict={x:xdata})
    print(pred)
    for p, y in zip(pred, ydata.flatten()):
        print("[{}] 예측: {} 실제 y: {}".format(p==int(y), p, int(y)))

step:  0 cv:  3.9725056 acc:  0.13861386
step:  1000 cv:  0.59789604 acc:  0.84158415
step:  2000 cv:  0.38526583 acc:  0.8910891
step:  3000 cv:  0.29626173 acc:  0.9108911
step:  4000 cv:  0.23855709 acc:  0.9306931
step:  5000 cv:  0.19765733 acc:  0.96039605
step:  6000 cv:  0.16769 acc:  0.97029704
step:  7000 cv:  0.14512414 acc:  0.97029704
step:  8000 cv:  0.12764785 acc:  0.980198
step:  9000 cv:  0.11375734 acc:  0.990099
step:  10000 cv:  0.10247124 acc:  0.990099
[0 0 3 0 0 0 0 3 3 0 0 1 3 6 6 6 1 0 3 0 1 1 0 1 5 4 4 0 0 0 5 0 0 1 3 0 0
 1 3 5 5 1 5 1 0 0 6 0 0 0 0 5 4 6 0 0 1 1 1 1 3 3 2 0 0 0 0 0 0 0 0 1 6 3
 0 0 2 6 1 1 2 6 3 1 0 6 3 1 5 4 1 2 3 0 0 1 0 5 0 6 1]
[True] 예측: 0 실제 y: 0
[True] 예측: 0 실제 y: 0
[True] 예측: 3 실제 y: 3
[True] 예측: 0 실제 y: 0
[True] 예측: 0 실제 y: 0
[True] 예측: 0 실제 y: 0
[True] 예측: 0 실제 y: 0
[True] 예측: 3 실제 y: 3
[True] 예측: 3 실제 y: 3
[True] 예측: 0 실제 y: 0
[True] 예측: 0 실제 y: 0
[True] 예측: 1 실제 y: 1
[True] 예측: 3 실제 y: 3
[True] 예측: 6 실제 y: 6
[True] 예측: 6 실제 y: 6

In [69]:
prediction

<tf.Tensor 'ArgMax_4:0' shape=(?,) dtype=int64>

In [70]:
cost_

<tf.Tensor 'softmax_cross_entropy_with_logits_sg_3/Reshape_2:0' shape=(?,) dtype=float32>