In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

In [0]:
model = Sequential()
model.add(Dense(3, input_dim=4, activation='softmax'))

In [0]:
tf.reset_default_graph()

# FFNN 
from keras.layers import Input,Dense
from keras.models import Model

inputs = Input(shape=(10,)) # 입력 : 10개
hid1 = Dense(32, activation='relu')(inputs)
hid2 = Dense(32, activation='relu')(hid1)
outputs = Dense(1,activation='sigmoid')(hid2)
model = Model(inputs=inputs, outputs = outputs)

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['acc'])
# model.fit(xdata, ylabel)

model.summary()

W0823 00:21:35.888007 139655746168704 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0823 00:21:35.916892 139655746168704 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                352       
_________________________________________________________________
dense_2 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 1,441
Trainable params: 1,441
Non-trainable params: 0
_________________________________________________________________


In [0]:
# RNN

In [0]:
from keras.layers import LSTM

tf.reset_default_graph()

inputs = Input(shape=(30,1)) # 30 : time-step
lstm_layer = LSTM(10)(inputs)
x = Dense(10, activation='relu')(lstm_layer)
outputs = Dense(1, activation='sigmoid')(x)
model = Model(inputs=inputs, outputs=outputs)

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 30, 1)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 10)                480       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


# RNN TERMS

In [0]:
# input data : batch_size
# length : time_step
# input data dimension : input_dim
# size of hidden layer : hidden_size

from keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [0]:
from keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10)))
# 2 => time_step / 10 => input_dim
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [0]:
from keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_length=2, input_dim=10))
# 2 => time_step / 10 => input_dim
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `SimpleRNN` call to the Keras 2 API: `SimpleRNN(3, input_shape=(2, 10))`
  after removing the cwd from sys.path.


# Numpy로 계산해보장!

In [0]:
import numpy as np
timesteps = 10 # 시점, 단어의 숫자(한 문장), char의 수(한 단어)
# 주식 예측 모델 : timesteps = 7 => 일주일간의 주식 변동패턴을 기반으로 : 오늘 주식을 예측
input_dim = 4 # 단어가 4개인 벡터(corpus)
hidden_size = 8 # hidden vector의 크기 : cell의 크기
inputs = np.random.random((timesteps, input_dim))
inputs.shape

(10, 4)

In [0]:
inputs

array([[0.7899475 , 0.4384779 , 0.64190545, 0.56164313],
       [0.72907166, 0.4058659 , 0.09205936, 0.11695867],
       [0.28766249, 0.73756768, 0.53758389, 0.15627927],
       [0.18249796, 0.01711066, 0.56060282, 0.73090805],
       [0.0252137 , 0.96343423, 0.76336394, 0.62319838],
       [0.99185579, 0.57069079, 0.17336086, 0.78425423],
       [0.9675186 , 0.92941639, 0.70064814, 0.56679905],
       [0.2062641 , 0.4343883 , 0.26358744, 0.14279219],
       [0.37463483, 0.30057194, 0.9469306 , 0.3922811 ],
       [0.25280841, 0.58392658, 0.26674484, 0.42590477]])

In [0]:
# 초기 은닉 상태를 0으로 초기화
hidden_state_t = np.zeros((hidden_size, ))

In [0]:
# 가중치
# wx : 입력에 대한 가중치
wx = np.random.random((hidden_size, input_dim))
# wh : 은닉층
wh = np.random.random((hidden_size, hidden_size))
# b : 바이어스
b = np.random.random((hidden_size,))
print(np.shape(wx))

(8, 4)


In [0]:
# 메모리 셀 동작
total_hidden_states = []
for input_t in inputs:
  output_t = np.tanh(np.dot(wx,input_t) + np.dot(wh,hidden_state_t) + b)
  # wx*xt + wh+ht-1 + b
  total_hidden_states.append(list(output_t))
  # print(np.shape(total_hidden_states))
  hidden_state_t = output_t
print(total_hidden_states)
  

[[0.978100900310307, 0.8957520269986841, 0.9209260488614334, 0.9231941084812416, 0.9605219888631561, 0.9639839614105701, 0.8211058811311098, 0.9534351872999134], [0.9999710300214459, 0.999949847910954, 0.9998099081722185, 0.9999827600502681, 0.9999375257189559, 0.999911042339356, 0.999224722068008, 0.9995655650941068], [0.999987492256645, 0.9999837992383873, 0.9999228227999601, 0.9999904939324088, 0.9999645125874508, 0.9999526245970529, 0.9995513610155253, 0.9999017144992184], [0.9999871750298304, 0.9999821380027761, 0.999756369841954, 0.9999944238972563, 0.9999610073472732, 0.9999529914714169, 0.9996066390957331, 0.9998878659666278], [0.9999937721741204, 0.9999912789108574, 0.9999390045675902, 0.9999950768255488, 0.999971455265031, 0.999976766773684, 0.9995804041580362, 0.9999751427985034], [0.999995725854116, 0.9999865535656772, 0.9999358626893322, 0.9999983687208768, 0.9999888111847512, 0.9999901427723833, 0.9997456428047122, 0.999965199331703], [0.9999978427356433, 0.99999290789594

In [0]:
np.shape(total_hidden_states)

(10, 8)

In [0]:
text = \
"""
멀티캠퍼스에 있는 교육생들이 공부하고 있다\n
교육생들은 딥러닝을 하고있다\n
결석한 교육생도 있고 지각하는 교육생도 있다\n

"""
# xdata : 멀티캠퍼스에 / ydata : 있는
# 멀티캠퍼스에 있는 / 교육생들이
# 멀티캠퍼스에, 3 / 있는 교육생들이 공부하고

In [0]:
from keras.preprocessing.text import Tokenizer

In [0]:
t = Tokenizer()
t.fit_on_texts([text])

In [0]:
t.texts_to_sequences([text])

[[3, 4, 5, 6, 1, 7, 8, 9, 10, 2, 11, 12, 2, 1]]

In [0]:
print(t.word_index) # index number는 1부터 시작!

{'있다': 1, '교육생도': 2, '멀티캠퍼스에': 3, '있는': 4, '교육생들이': 5, '공부하고': 6, '교육생들은': 7, '딥러닝을': 8, '하고있다': 9, '결석한': 10, '있고': 11, '지각하는': 12}


In [0]:
vocab_size = len(t.word_index)+1 # 단어집합 크기 : 13

In [0]:
for line in text.split("\n"):
  print(t.texts_to_sequences([line])[0])

[]
[3, 4, 5, 6, 1]
[]
[7, 8, 9]
[]
[10, 2, 11, 12, 2, 1]
[]
[]
[]


In [0]:
sequences = []
for line in text.split("\n"):
#   print(t.texts_to_sequences([line])[0])
  encoded = t.texts_to_sequences([line])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)
    print(sequence) # 이런식으로 단어들의 sequence를 출력!

[3, 4]
[3, 4, 5]
[3, 4, 5, 6]
[3, 4, 5, 6, 1]
[7, 8]
[7, 8, 9]
[10, 2]
[10, 2, 11]
[10, 2, 11, 12]
[10, 2, 11, 12, 2]
[10, 2, 11, 12, 2, 1]


In [0]:
sequences

[[3, 4],
 [3, 4, 5],
 [3, 4, 5, 6],
 [3, 4, 5, 6, 1],
 [7, 8],
 [7, 8, 9],
 [10, 2],
 [10, 2, 11],
 [10, 2, 11, 12],
 [10, 2, 11, 12, 2],
 [10, 2, 11, 12, 2, 1]]

In [0]:
len(sequences)

11

In [0]:
print(max(len(s) for s in sequences)) # sequences 내부 리스트 중 가장 긴 놈의 길이!
max_len = max(len(s) for s in sequences)

6


In [0]:
from keras.preprocessing.sequence import pad_sequences
pad_sequences(sequences, maxlen=max_len, padding='post')

array([[ 3,  4,  0,  0,  0,  0],
       [ 3,  4,  5,  0,  0,  0],
       [ 3,  4,  5,  6,  0,  0],
       [ 3,  4,  5,  6,  1,  0],
       [ 7,  8,  0,  0,  0,  0],
       [ 7,  8,  9,  0,  0,  0],
       [10,  2,  0,  0,  0,  0],
       [10,  2, 11,  0,  0,  0],
       [10,  2, 11, 12,  0,  0],
       [10,  2, 11, 12,  2,  0],
       [10,  2, 11, 12,  2,  1]], dtype=int32)

In [0]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
sequences

array([[ 0,  0,  0,  0,  3,  4],
       [ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  3,  4,  5,  6],
       [ 0,  3,  4,  5,  6,  1],
       [ 0,  0,  0,  0,  7,  8],
       [ 0,  0,  0,  7,  8,  9],
       [ 0,  0,  0,  0, 10,  2],
       [ 0,  0,  0, 10,  2, 11],
       [ 0,  0, 10,  2, 11, 12],
       [ 0, 10,  2, 11, 12,  2],
       [10,  2, 11, 12,  2,  1]], dtype=int32)

In [0]:
xdata = sequences[:,:-1]
ylabel = sequences[:,-1].reshape(-1,1)

In [0]:
xdata

array([[ 0,  0,  0,  0,  3],
       [ 0,  0,  0,  3,  4],
       [ 0,  0,  3,  4,  5],
       [ 0,  3,  4,  5,  6],
       [ 0,  0,  0,  0,  7],
       [ 0,  0,  0,  7,  8],
       [ 0,  0,  0,  0, 10],
       [ 0,  0,  0, 10,  2],
       [ 0,  0, 10,  2, 11],
       [ 0, 10,  2, 11, 12],
       [10,  2, 11, 12,  2]], dtype=int32)

In [0]:
ylabel

array([[ 4],
       [ 5],
       [ 6],
       [ 1],
       [ 8],
       [ 9],
       [ 2],
       [11],
       [12],
       [ 2],
       [ 1]], dtype=int32)

In [0]:
from keras.layers import Embedding
from keras.utils.np_utils import *

In [0]:
y_ohe = to_categorical(ylabel)

In [0]:
y_ohe

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [0]:
vocab_size

13

In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 단어집합 크기(즉, 몇개?), 10차원으로, input length는 5 (6-1) 
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 5, 10)             130       
Total params: 130
Trainable params: 130
Non-trainable params: 0
_________________________________________________________________


In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 단어집합 크기(즉, 몇개?), 10차원으로, input length는 5 (6-1) = time step!
# 즉, (None, 5, 13) => (None, 5, 10)으로 변경
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.fit(xdata,y_ohe, epochs=150, verbose=2)

Epoch 1/150
 - 1s - loss: 2.5597 - acc: 0.1818
Epoch 2/150
 - 0s - loss: 2.5511 - acc: 0.1818
Epoch 3/150
 - 0s - loss: 2.5425 - acc: 0.1818
Epoch 4/150
 - 0s - loss: 2.5339 - acc: 0.2727
Epoch 5/150
 - 0s - loss: 2.5252 - acc: 0.3636
Epoch 6/150
 - 0s - loss: 2.5164 - acc: 0.3636
Epoch 7/150
 - 0s - loss: 2.5075 - acc: 0.3636
Epoch 8/150
 - 0s - loss: 2.4984 - acc: 0.3636
Epoch 9/150
 - 0s - loss: 2.4890 - acc: 0.3636
Epoch 10/150
 - 0s - loss: 2.4793 - acc: 0.3636
Epoch 11/150
 - 0s - loss: 2.4693 - acc: 0.3636
Epoch 12/150
 - 0s - loss: 2.4590 - acc: 0.3636
Epoch 13/150
 - 0s - loss: 2.4482 - acc: 0.3636
Epoch 14/150
 - 0s - loss: 2.4370 - acc: 0.3636
Epoch 15/150
 - 0s - loss: 2.4254 - acc: 0.3636
Epoch 16/150
 - 0s - loss: 2.4133 - acc: 0.3636
Epoch 17/150
 - 0s - loss: 2.4006 - acc: 0.3636
Epoch 18/150
 - 0s - loss: 2.3875 - acc: 0.4545
Epoch 19/150
 - 0s - loss: 2.3738 - acc: 0.4545
Epoch 20/150
 - 0s - loss: 2.3596 - acc: 0.4545
Epoch 21/150
 - 0s - loss: 2.3448 - acc: 0.4545
E

In [0]:
def word_gen(model, t, curr_word, num): # model, tokenizer, 입력단어, 개수
  ini_word = curr_word
  sent = ''
  for _ in range(num):
    encoded = t.texts_to_sequences([curr_word])[0] # 스페이스로 단어 구분해서 그걸 인덱스로 치환해서 리스트로 리턴
    print(encoded)
    encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre') # 그걸 사이즈 5(input size)로 변경해줌 : pad_sequences를 쓰면 맨 뒤에놈 5개만 가져와주는군! 개이득!
    print("변경!",encoded)
    res = model.predict_classes(encoded) # 다음 글자의 인덱스 번호!
    print(res)
    for word, index in t.word_index.items():
      if res==index:
        break
    curr_word = curr_word+' '+word
    sent = sent+' '+word
  sent = ini_word+sent
  return sent
    
    
print(word_gen(model, t, '멀티캠퍼스에', 6))

[3]
변경! [[0 0 0 0 3]]
[4]
[3, 4]
변경! [[0 0 0 3 4]]
[5]
[3, 4, 5]
변경! [[0 0 3 4 5]]
[6]
[3, 4, 5, 6]
변경! [[0 3 4 5 6]]
[1]
[3, 4, 5, 6, 1]
변경! [[3 4 5 6 1]]
[11]
[3, 4, 5, 6, 1, 11]
변경! [[ 4  5  6  1 11]]
[12]
멀티캠퍼스에 있는 교육생들이 공부하고 있다 있고 지각하는


# NYT article

In [0]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/ArticlesApril2018.csv")
df

articleID  ...                                             webURL
0     5adf6684068401528a2aa69b  ...  https://www.nytimes.com/2018/04/24/sports/foot...
1     5adf653f068401528a2aa697  ...  https://www.nytimes.com/2018/04/24/climate/epa...
2     5adf4626068401528a2aa628  ...  https://www.nytimes.com/2018/04/24/dining/noma...
3     5adf40d2068401528a2aa619  ...  https://www.nytimes.com/2018/04/24/world/europ...
4     5adf3d64068401528a2aa60f  ...  https://www.nytimes.com/2018/04/24/world/canad...
5     5adf341f068401528a2aa5e8  ...  https://www.nytimes.com/2018/04/24/us/politics...
6     5adf2a0f068401528a2aa5c8  ...  https://www.nytimes.com/2018/04/24/us/californ...
7     5adf26cf068401528a2aa5c1  ...  https://www.nytimes.com/2018/04/24/us/politics...
8     5adf2108068401528a2aa5b3  ...  https://www.nytimes.com/2018/04/24/insider/how...
9     5adedaa8068401528a2aa4e6  ...  https://www.nytimes.com/2018/04/24/learning/is...
10    5adf0063068401528a2aa552  ...  https://www.nytimes.com/2018/04/24/well/think-...
11    5adf0024068401528a2aa551  ...  https://www.nytimes.com/2018/04/24/nyregion/ne...
12    5adef286068401528a2aa537  ...  https://www.nytimes.com/2018/04/24/realestate/...
13    5adef237068401528a2aa532  ...  https://www.nytimes.com/2018/04/24/business/fo...
14    5adef237068401528a2aa531  ...  https://www.nytimes.com/2018/04/24/us/politics...
15    5adef230068401528a2aa527  ...  https://www.nytimes.com/2018/04/24/magazine/on...
16    5adef233068401528a2aa52c  ...  https://www.nytimes.com/2018/04/24/us/sex-abus...
17    5adef22f068401528a2aa525  ...  https://www.nytimes.com/2018/04/24/arts/berlin...
18    5adef226068401528a2aa520  ...  https://www.nytimes.com/2018/04/24/us/gun-owne...
19    5adef226068401528a2aa51f  ...  https://www.nytimes.com/2018/04/24/books/revie...
20    5adef221068401528a2aa517  ...  https://www.nytimes.com/2018/04/24/magazine/ji...
21    5adef221068401528a2aa516  ...  https://www.nytimes.com/2018/04/24/magazine/ho...
22    5adef218068401528a2aa514  ...  https://www.nytimes.com/2018/04/24/nyregion/ne...
23    5aded6a7068401528a2aa4e0  ...  https://www.nytimes.com/2018/04/24/learning/pr...
24    5adec85b068401528a2aa4c1  ...  https://www.nytimes.com/2018/04/24/learning/24...
25    5adeae5b068401528a2aa48c  ...  https://www.nytimes.com/2018/04/24/well/eat/e-...
26    5adea843068401528a2aa47a  ...  https://www.nytimes.com/2018/04/23/business/gr...
27    5ade8fa4068401528a2aa465  ...  https://www.nytimes.com/2018/04/23/crosswords/...
28    5ade8c22068401528a2aa460  ...  https://www.nytimes.com/2018/04/23/theater/rev...
29    5ade8a5b068401528a2aa45d  ...  https://www.nytimes.com/2018/04/23/business/de...
...                        ...  ...                                                ...
1294  5ae76aaf068401528a2ab804  ...  https://www.nytimes.com/2018/04/30/well/family...
1295  5ae76cd6068401528a2ab809  ...  https://www.nytimes.com/2018/04/30/business/de...
1296  5ae76fcc068401528a2ab818  ...  https://www.nytimes.com/2018/04/30/opinion/rob...
1297  5ae77514068401528a2ab824  ...  https://www.nytimes.com/2018/04/30/world/ameri...
1298  5ae77c97068401528a2ab835  ...  https://www.nytimes.com/2018/04/30/world/middl...
1299  5ae788d2068401528a2ab85c  ...  https://www.nytimes.com/2018/04/30/business/th...
1300  5ae791e4068401528a2ab876  ...  https://www.nytimes.com/2018/04/30/nyregion/me...
1301  5ae79a1a068401528a2ab88b  ...  https://www.nytimes.com/2018/04/30/science/mar...
1302  5ae79ecd068401528a2ab893  ...  https://www.nytimes.com/2018/04/30/opinion/rep...
1303  5ae79f0c068401528a2ab894  ...  https://www.nytimes.com/2018/04/30/world/ameri...
1304  5ae7a00b068401528a2ab896  ...  https://www.nytimes.com/2018/04/30/opinion/lov...
1305  5ae7a68c068401528a2ab8a5  ...  https://www.nytimes.com/2018/04/30/opinion/tmo...
1306  5ae7a6c6068401528a2ab8a8  ...  https://www.nytimes.com/2018/04/30/technology/...
1307  5ae7a739068401528a2ab8a9  ...  https://www.nytimes.com/2018/04/30/opinion/tru...
1308  5ae7ab8206840

In [0]:
df['headline'].isnull().values.any() # 어느 하나라도 null이면 True

False

In [0]:
headline = []
headline.extend(list(df.headline.values))
headline

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown',
 'Unknown',
 'Unknown',
 'Unknown',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?',
 'Commuter Reprogramming',
 'Unknown',
 'Unknown',
 'Ford Changed Leaders, Looking for a Lift. It’s Still Looking.',
 'Romney Failed to Win at Utah Convention, But Few Believe He’s Doomed',
 'Chain Reaction',
 'He Forced the Vatican to Investigate Sex Abuse. Now He’s Meeting With Pope Francis.',
 'In Berlin, artists find a home',
 'Unknown',
 'The Right Stuff',
 'Jimmy Carter Knows What North Korea Wants',
 'The Truth Is Out There',
 'New Jersey Ruling Could Reignite Battle Over Church-State Separation',
 'Procrastinating',
 'Word + Quiz: dilatory',
 'My Life-Threatening Bout With E. Coli Food Poisoning',
 'Choosing Brexit, a Town Yearned for Its Seafa

In [0]:
headline = [n for n in headline if n != 'Unknown']
len(headline)
headline # unknown 제목 날리기

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?',
 'Commuter Reprogramming',
 'Ford Changed Leaders, Looking for a Lift. It’s Still Looking.',
 'Romney Failed to Win at Utah Convention, But Few Believe He’s Doomed',
 'Chain Reaction',
 'He Forced the Vatican to Investigate Sex Abuse. Now He’s Meeting With Pope Francis.',
 'In Berlin, artists find a home',
 'The Right Stuff',
 'Jimmy Carter Knows What North Korea Wants',
 'The Truth Is Out There',
 'New Jersey Ruling Could Reignite Battle Over Church-State Separation',
 'Procrastinating',
 'Word + Quiz: dilatory',
 'My Life-Threatening Bout With E. Coli Food Poisoning',
 'Choosing Brexit, a Town Yearned for Its Seafaring Past, and Muddied Its Future',
 'A Quote Disproved',
 'Hot Stuff Turns Cold',
 'At the Top,

In [0]:
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [0]:
from string import punctuation
import re
def mypreprocessing(s): # 점 제거, 소문자 변환
  s = s.lower()
  tmp = ''
  for char in s:
    if char not in punctuation:
      tmp += char
  # 전처리된 문장 리턴
  print(''.join(ch for ch in s if ch not in punctuation))
  return tmp

text = [mypreprocessing(x) for x in headline]

former nfl cheerleaders’ settlement offer 1 and a meeting with goodell
epa to unveil a new rule its effect less science in policymaking
the new noma explained
how a bag of texas dirt  became a times tradition
is school a place for selfexpression
commuter reprogramming
ford changed leaders looking for a lift it’s still looking
romney failed to win at utah convention but few believe he’s doomed
chain reaction
he forced the vatican to investigate sex abuse now he’s meeting with pope francis
in berlin artists find a home
the right stuff
jimmy carter knows what north korea wants
the truth is out there
new jersey ruling could reignite battle over churchstate separation
procrastinating
word  quiz dilatory
my lifethreatening bout with e coli food poisoning
choosing brexit a town yearned for its seafaring past and muddied its future
a quote disproved
hot stuff turns cold
at the top the pay gap may be gone
years of bizarre behavior but he got guns back
will the court stand up to mr trump
hope in

In [0]:
# vacabulary 작성(단어집합)
t = Tokenizer()
t.fit_on_texts(text)
t.word_index

{'the': 1,
 'a': 2,
 'to': 3,
 'of': 4,
 'in': 5,
 'for': 6,
 'and': 7,
 'on': 8,
 'is': 9,
 'with': 10,
 'trump': 11,
 'as': 12,
 'at': 13,
 'new': 14,
 'from': 15,
 'how': 16,
 'it': 17,
 'an': 18,
 'be': 19,
 'that': 20,
 'season': 21,
 'us': 22,
 'you': 23,
 'what': 24,
 'episode': 25,
 'can': 26,
 'your': 27,
 'he': 28,
 'not': 29,
 'his': 30,
 'are': 31,
 'teaching': 32,
 'out': 33,
 'was': 34,
 'no': 35,
 'by': 36,
 'trump’s': 37,
 'has': 38,
 'war': 39,
 'over': 40,
 'may': 41,
 'into': 42,
 'more': 43,
 'now': 44,
 'why': 45,
 'who': 46,
 'about': 47,
 'recap': 48,
 'activities': 49,
 '1': 50,
 'we': 51,
 'do': 52,
 'women': 53,
 'when': 54,
 'syria': 55,
 'trade': 56,
 'it’s': 57,
 '2': 58,
 'or': 59,
 'will': 60,
 'i': 61,
 'have': 62,
 'just': 63,
 'but': 64,
 'home': 65,
 'up': 66,
 'this': 67,
 'one': 68,
 'off': 69,
 'house': 70,
 'president': 71,
 'gop': 72,
 'our': 73,
 'long': 74,
 'facebook': 75,
 'case': 76,
 'life': 77,
 'end': 78,
 'some': 79,
 'power': 80,
 'say'

In [0]:
vocab_size = len(t.word_index) + 1 # 단어 집합의 크기
vocab_size

3620

In [0]:
sequences = []
for line in text: # 1214개의 line
  encoded = t.texts_to_sequences([line])[0]
#   print(len(encoded))
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)
print(sequences[:20])

[[95, 263], [95, 263, 1100], [95, 263, 1100, 1101], [95, 263, 1100, 1101, 572], [95, 263, 1100, 1101, 572, 50], [95, 263, 1100, 1101, 572, 50, 7], [95, 263, 1100, 1101, 572, 50, 7, 2], [95, 263, 1100, 1101, 572, 50, 7, 2, 365], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10], [95, 263, 1100, 1101, 572, 50, 7, 2, 365, 10, 1102], [96, 3], [96, 3, 1103], [96, 3, 1103, 2], [96, 3, 1103, 2, 14], [96, 3, 1103, 2, 14, 573], [96, 3, 1103, 2, 14, 573, 85], [96, 3, 1103, 2, 14, 573, 85, 1104], [96, 3, 1103, 2, 14, 573, 85, 1104, 366], [96, 3, 1103, 2, 14, 573, 85, 1104, 366, 367], [96, 3, 1103, 2, 14, 573, 85, 1104, 366, 367, 5]]


In [0]:
np.shape(sequences)

(7809,)

In [0]:
max_len = max(len(s) for s in sequences) # 최대길이 24
max_len

24

In [0]:
from keras.preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences,maxlen=max_len, padding='pre')
np.shape(sequences)

(7809, 24)

In [0]:
xdata = sequences[:,:-1]
ylabel = sequences[:,-1].reshape(-1,1)
y_ohe = to_categorical(ylabel)

In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 단어집합 크기(즉, 몇개?), 10차원으로, input length는 5 (6-1) = time step!
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.fit(xdata,y_ohe, epochs=150, verbose=2)

In [0]:
# with tf.Session() as sess:
#   with sess.as_default():
#     with sess.graph.as_default():
#       model = Sequential()
#       model.add(Embedding(vocab_size, 128, input_length=max_len-1))
#       model.add(LSTM(128))
#       model.add(Dense(vocab_size, activation='softmax'))
#       model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['acc'])
#       model.fit(xdata, y_ohe, epochs=20, verbose=2)

In [201]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

tf.reset_default_graph()

model = Sequential()
model.add(Embedding(vocab_size, 128, input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['acc'])
model.fit(xdata, y_ohe, epochs=100, verbose=1)

Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x7f037aefe710>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1473, in __del__
    self._session._session, self._handle)
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.


Epoch 1/100
7809/7809 [==============================] - 16s 2ms/sample - loss: 7.6699 - acc: 0.0264
Epoch 2/100
7809/7809 [==============================] - 15s 2ms/sample - loss: 7.0715 - acc: 0.0361
Epoch 3/100
7809/7809 [==============================] - 15s 2ms/sample - loss: 6.8464 - acc: 0.0447
Epoch 4/100
7809/7809 [==============================] - 15s 2ms/sample - loss: 6.6455 - acc: 0.0484
Epoch 5/100
7809/7809 [==============================] - 16s 2ms/sample - loss: 6.4251 - acc: 0.0540
Epoch 6/100
7809/7809 [==============================] - 16s 2ms/sample - loss: 6.1841 - acc: 0.0626
Epoch 7/100
7809/7809 [==============================] - 15s 2ms/sample - loss: 5.9321 - acc: 0.0731
Epoch 8/100
7809/7809 [==============================] - 16s 2ms/sample - loss: 5.6846 - acc: 0.0862
Epoch 9/100
7809/7809 [==============================] - 16s 2ms/sample - loss: 5.4380 - acc: 0.0983
Epoch 10/100
7809/7809 [==============================] - 15s 2ms/sample - loss: 5.1934 - a

In [0]:
import os
model.save(os.path.join("/content/drive/My Drive/Colab Notebooks","nyt_0823.h5"))

In [0]:
def article_gen(model, t, curr_word, num): # model, tokenizer, 입력단어, 개수
  ini_word = curr_word
  sent = ''
  for _ in range(num):
    encoded = t.texts_to_sequences([curr_word])[0] # 스페이스로 단어 구분해서 그걸 인덱스로 치환해서 리스트로 리턴
#     print(encoded)
    encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre') # 그걸 사이즈 5(input size)로 변경해줌 : pad_sequences를 쓰면 맨 뒤에놈 5개만 가져와주는군! 개이득!
#     print("변경!",encoded)
    res = model.predict_classes(encoded) # 다음 글자의 인덱스 번호!
#     print(res)
    for word, index in t.word_index.items():
      if res==index:
        break
    curr_word = curr_word+' '+word
    sent = sent+' '+word
  sent = ini_word+sent
  return sent

In [208]:
article_gen(model, t, 'love', 10)

'love being married beating cancer study shows the power of immune'