In [84]:
from bs4 import BeautifulSoup
import numpy as np
import urllib.request as req
from urllib.request import urlopen

In [193]:
import PIL.Image as pilimg
im1_1 = pilimg.open("C:/datasets/numpic/1_1.png")
im1_2 = pilimg.open("C:/datasets/numpic/1_2.png")
im2_1 = pilimg.open("C:/datasets/numpic/2_1.png")
im2_2 = pilimg.open("C:/datasets/numpic/2_2.png")

In [194]:
type(im1_1)

PIL.PngImagePlugin.PngImageFile

In [195]:
im1_1

In [196]:
np.array(im1_1).min()

0

In [197]:
im1_1 = im1_1.convert('L') # grayscale로 만들어주기
im1_1

In [198]:
px_im1_1 = np.array(im1_1)

In [199]:
px_im1_1.shape

(20, 20)

In [200]:
px_im1_2 = np.array(im1_2.convert('L'))
px_im2_1 = np.array(im2_1.convert('L'))
px_im2_2 = np.array(im2_2.convert('L'))

In [201]:
px_im1_1 = px_im1_1.flatten().astype(np.float64)
px_im1_2 = px_im1_2.flatten().astype(np.float64)
px_im2_1 = px_im2_1.flatten().astype(np.float64)
px_im2_2 = px_im2_2.flatten().astype(np.float64)
# 쫙 필때는 flatten

In [202]:
px_im1_1.shape

(400,)

In [203]:
# overflow 조심!
from numpy.linalg import norm
def cos_sim(x,y):
    x = x.astype(np.float64)
    y = y.astype(np.float64)
    res = (np.dot(x,y)) / ((norm(x)*norm(y)))
    return res

In [204]:
res11_11 = cos_sim(px_im1_1,px_im1_1)

In [205]:
np.dot(px_im1_1,px_im1_1)

14676245.0

In [206]:
np.sqrt(np.dot(px_im1_1,px_im1_1)) * np.sqrt(np.dot(px_im1_1,px_im1_1))

14676245.000000002

In [207]:
np.dot(px_im1_1,px_im1_1)/(np.sqrt(np.dot(px_im1_1,px_im1_1)) * np.sqrt(np.dot(px_im1_1,px_im1_1)))

0.9999999999999999

In [208]:
res11_11 # overflow?

0.9999999999999999

In [209]:
piclist = [px_im1_1,px_im1_2,px_im2_1,px_im2_2]

In [210]:
piclist[0].mean()

149.5875

In [211]:
resArr = np.zeros(16).reshape(4,-1)
for i in range(len(piclist)):
    for k in range(len(piclist)):
        resArr[i,k] = cos_sim(piclist[i],piclist[k])

In [212]:
resArr.max()

1.0000000000000002

In [213]:
resArr.min()

0.4321090798827188

In [214]:
resArr

array([[1.        , 0.95979662, 0.66916861, 0.46863421],
       [0.95979662, 1.        , 0.67038946, 0.43210908],
       [0.66916861, 0.67038946, 1.        , 0.50143722],
       [0.46863421, 0.43210908, 0.50143722, 1.        ]])

In [215]:
piclist[0].shape

(400,)

In [222]:
from sklearn.metrics.pairwise import linear_kernel # 얘는 쓰는 이유 뭐니?
tmp = piclist[0].reshape(1,-1)
cos_sim = linear_kernel(tmp,tmp)
cos_sim

array([[14676245.]])

In [217]:
norm(np.array([3,4]))

5.0

In [218]:
a = np.array([3,4])

In [157]:
a.shape

(2,)

In [158]:
np.dot(a,a)

25

In [220]:
linear_kernel(a.reshape(1,-1),a.reshape(1,-1))

array([[25.]])