In [0]:
import numpy as np

In [0]:
arr = np.array([1,2,3])

In [0]:
print(type(arr))

<class 'numpy.ndarray'>


In [0]:
for i in arr:
  print(i)

1
2
3


In [0]:
arr

array([1, 2, 3])

In [0]:
ans = []

In [0]:
for i in arr:
  ans.append(2*i)

print(ans)

[2, 4, 6]


In [0]:
print(2*arr)

[2 4 6]


In [0]:
li = [1,2,3]

In [0]:
li

[1, 2, 3]

In [0]:
print(li*2)

[1, 2, 3, 1, 2, 3]


In [0]:
a = np.array([1,2])

In [0]:
b = np.array([10,20])

In [0]:
3*a+b

array([13, 26])

In [0]:
a==2

array([False,  True])

In [0]:
arr == 2

array([False,  True, False])

In [0]:
(arr < 2) & (arr > 0) # (arr < 2) and (arr > 0) 이건 오류나네

array([ True, False, False])

In [0]:
c = np.array([[1,2,3],[4,5,6]])

In [0]:
c.shape

(2, 3)

In [0]:
c.ndim

2

In [0]:
c.shape[0]

2

In [0]:
c.shape[1]

3

In [0]:
len(c[0])

3

In [0]:
len(c)

2

In [0]:
a3 = np.array([1,2,3,4,5])

In [31]:
print(a3[-1])

5


In [0]:
a3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [34]:
a3[0][1]

2

In [35]:
a3[0,1]

2

In [39]:
type((a3.shape, a3.ndim))

tuple

In [40]:
a3.shape

(2, 5)

In [41]:
a3[-1,-1]

10

In [42]:
a3[-1,-2]

9

In [50]:
a3[1,:]

array([ 6,  7,  8,  9, 10])

In [52]:
np.arange(2,23,4)

array([ 2,  6, 10, 14, 18, 22])

In [55]:
# f(x) = w1x1 + w2x2 ... + wnxn + b : 다중선형회귀식
a = np.zeros((5,2),dtype=np.int8) # dtype의 null option은 float
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [0]:
b = np.empty((5,2))

In [58]:
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
np.linspace(0,100,5) # 선형공간을 만들 때 사용 # 0 ~ 100 까지 5개의 구간으로 분할할 때 사용

array([  0.,  25.,  50.,  75., 100.])

In [49]:
np.array([a3[0,-1],a3[1,0]])

array([5, 6])

In [47]:
print(a3[1,0:2])

[6 7]
