In [4]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)
## 그래프 생성 부분
xtrain = np.array([[1.,1.,1.],[1.,2.,3.]]) # 하나당 하나의 b까지 포함
ytrain = np.array([1.,2.,3.]).reshape(1,-1)
x = tf.placeholder(dtype=tf.float32, shape=[2,None]) 
y = tf.placeholder(dtype=tf.float32, shape=[1,None])
# b = tf.Variable(tf.random_uniform([1,1]), name='bias') # 이렇게 해야 2차원으로 만들어지네!
w = tf.Variable([[1.,2.]], name='weight')
hf = tf.matmul(w,x)
cost = tf.reduce_mean(tf.square(hf-y))

lr = 0.001
gradient_b = tf.reduce_mean(hf-y) # 요기가 잘못!!! 위의 한줄만 곱해줘야!!
gradient_w = tf.reduce_mean((hf-y)*xtrain[1])
descent = w - tf.constant([gradient_b, gradient_w])
update = tf.assign(w,descent)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

TypeError: List of Tensors when single Tensor expected

In [3]:
w

<tf.Variable 'weight_1:0' shape=(1, 2) dtype=float32_ref>

In [3]:
xtrain[1]

array([1., 2., 3.])

In [2]:
sess.run(hf,feed_dict={x:xtrain})

array([[3., 5., 7.]], dtype=float32)

In [3]:
sess.run(gradient_b, feed_dict={x:xtrain,y:ytrain})

3.0

In [4]:
sess.run(gradient_w, feed_dict={x:xtrain,y:ytrain})

6.6666665

In [5]:
sess.run(w)

array([[1., 2.]], dtype=float32)

In [6]:
sess.run(w - lr*tf.constant([[sess.run(gradient_b, feed_dict={x:xtrain,y:ytrain}),\
                              sess.run(gradient_w, feed_dict={x:xtrain,y:ytrain})]]),\
                             feed_dict={x:xtrain,y:ytrain})

array([[0.997    , 1.9933333]], dtype=float32)

In [7]:
sess.run(w)

array([[1., 2.]], dtype=float32)

In [8]:
sess.close()

In [5]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)
## 그래프 생성 부분
xtrain = np.array([[1.,1.,1.],[1.,2.,3.]]) # 하나당 하나의 b까지 포함
ytrain = np.array([1.,2.,3.]).reshape(1,-1)
x = tf.placeholder(dtype=tf.float32, shape=[2,None]) 
y = tf.placeholder(dtype=tf.float32, shape=[1,None])
# b = tf.Variable(tf.random_uniform([1,1]), name='bias') # 이렇게 해야 2차원으로 만들어지네!
w = tf.Variable([[1.,2.]], name='weight')
hf = tf.matmul(w,x)
cost = tf.reduce_mean(tf.square(hf-y))

lr = 0.001

In [7]:
gradient_b = tf.reduce_mean(hf-y) # 요기가 잘못!!! 위의 한줄만 곱해줘야!!
gradient_w = tf.reduce_mean((hf-y)*xtrain[1].reshape(1,-1))
descent = w - tf.Variable([[gradient_b, gradient_w]])
update = tf.assign(w,descent)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init,feed_dict={x:xtrain,y:ytrain})

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [2,?]
	 [[node Placeholder (defined at <ipython-input-1-83965940e8da>:8) ]]

Original stack trace for 'Placeholder':
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\user\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\user\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-83965940e8da>", line 8, in <module>
    x = tf.placeholder(dtype=tf.float32, shape=[2,None])
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7400, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [8]:
for step in range(2001):
    sess.run(update,feed_dict={x:xtrain,y:ytrain})
    if step%200==0:
        print("cost :{}, w:{}".format(sess.run(cost,feed_dict={x:xtrain,y:ytrain}),\
                                     sess.run(w,feed_dict={x:xtrain,y:ytrain})))

cost :199.1851806640625, w:[[-2.        -4.6666665]]
cost :11953669.0, w:[[ -602.     -1337.9993]]
cost :47619828.0, w:[[-1202.    -2671.336]]
cost :106999264.0, w:[[-1802.     -4004.6855]]
cost :190089072.0, w:[[-2402.     -5337.9897]]
cost :296890336.0, w:[[-3002.     -6671.2905]]
cost :427403264.0, w:[[-3602.     -8004.5913]]
cost :581636416.0, w:[[-4202.    -9337.976]]
cost :759585472.0, w:[[ -4802.    -10671.374]]
cost :961248960.0, w:[[ -5402.    -12004.772]]
cost :1186627072.0, w:[[ -6002.    -13338.171]]
