In [1]:
import tensorflow as tf
import numpy as np

In [4]:
xy = np.loadtxt('05train.txt',unpack=True,dtype='float32')

In [46]:
x_data = xy[:3].T # 행렬 곱셈

In [47]:
y_data = xy[3:].T

In [48]:
x_data.shape

(8, 3)

In [49]:
y_data.shape

(8, 3)

In [50]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])

In [51]:
W = tf.Variable(tf.zeros([3,3]))

In [52]:
hypothesis = tf.nn.softmax(tf.matmul(X,W))

In [67]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))
# reduction_indices = 0이면 열 합계 / 1이면 행합계!

In [88]:
question = -tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1)
q2 = Y*tf.log(hypothesis)

In [84]:
learning_rate = 0.01

In [85]:
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [86]:
init = tf.initialize_all_variables()

In [90]:
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(2001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step%200==0:
            feed = {X:x_data, Y:y_data}
            print('{:4} {:8.6}'.\
                  format(step,sess.run(cost,feed_dict=feed)), sess.run(W))
            # 마지막으로 그것들 다리 reduce_mean
            print(sess.run(question, feed_dict=feed)) 
            # 그리고 그것을 행별로 합계 - 한 행이 되었다!
            print(sess.run(q2, feed_dict=feed)) # 아 걍 element 곱
            print(sess.run(hypothesis, feed_dict=feed)) # 이거는 8 * 3 tensor
            # 아 8
    print("-------------------------------------------------")
    
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7]]})
    print("a :", a, sess.run(tf.argmax(a, 1)))         # a : [[ 0.68849683  0.26731509  0.04418806]] [0]

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4]]})
    print("b :", b, sess.run(tf.argmax(b, 1)))         # b : [[ 0.2432227   0.44183081  0.3149465 ]] [1]

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0]]})
    print("c :", c, sess.run(tf.argmax(c, 1)))         # c : [[ 0.02974809  0.08208466  0.8881672 ]] [2]
    
    d = sess.run(hypothesis, feed_dict={X: [[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
    print("d : ", *d, end=' ')
    print(sess.run(tf.argmax(d, 1)))
#     print(sess.run(question, feed_dict={X: [[1,2,3]]}))

   0  1.08376 [[-5.3576467e-04  4.7265403e-05  4.8849970e-04]
 [ 2.9685295e-03  1.3005361e-03 -4.2690635e-03]
 [ 2.9685295e-03  2.5505361e-03 -5.5190632e-03]]
[1.1340525  1.1439657  1.1552507  0.97498065 0.972582   0.97864646
 1.1580956  1.1524956 ]
[[-0.         -0.         -1.1340525 ]
 [-0.         -0.         -1.1439657 ]
 [-0.         -0.         -1.1552507 ]
 [-0.         -0.97498065 -0.        ]
 [-0.         -0.972582   -0.        ]
 [-0.         -0.97864646 -0.        ]
 [-1.1580956  -0.         -0.        ]
 [-1.1524956  -0.         -0.        ]]
[[0.30610174 0.37217146 0.3217268 ]
 [0.30788597 0.37356076 0.3185532 ]
 [0.3096429  0.37537852 0.31497857]
 [0.31231534 0.37719965 0.31048498]
 [0.31411153 0.37810552 0.307783  ]
 [0.30961934 0.37581944 0.31456116]
 [0.31408373 0.37854496 0.30737135]
 [0.31584755 0.37987754 0.30427486]]
 200 0.982526 [[-0.2067006  -0.06275596  0.26945657]
 [ 0.03499695 -0.07023653  0.03523967]
 [ 0.05167444  0.11340196 -0.16507642]]
[0.9512849  1.07

a : [[0.69419235 0.2612981  0.04450946]] [0]
b : [[0.23935877 0.4465029  0.3141383 ]] [1]
c : [[0.02840727 0.08610597 0.8854867 ]] [2]
d :  [0.69419235 0.26129812 0.04450946] [0.23935877 0.4465029  0.3141383 ] [0.02840727 0.08610597 0.8854867 ] [0 1 2]
