In [1]:
import numpy as np
import pandas as pd

## Numpy Basic

In [6]:
a = np.eye(8)

In [7]:
a[1,:]

array([0., 1., 0., 0., 0., 0., 0., 0.])

In [8]:
a[5,:]

array([0., 0., 0., 0., 0., 1., 0., 0.])

In [14]:
arr2d = np.arange(9).reshape(3,-1)
arr2d[:,0]

array([0, 3, 6])

In [17]:
arr2d[:,:1]

array([[0],
       [3],
       [6]])

In [18]:
b = np.arange(40).reshape(10,-1)
b[[3,2,1,9]] # iloc style

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [36, 37, 38, 39]])

In [24]:
arr = np.random.randn(5,3)
arr

array([[ 0.3106557 ,  0.6784504 , -0.66128384],
       [ 0.91224702, -0.92214898, -0.8218954 ],
       [ 0.29463868,  0.27366227, -0.01064161],
       [-0.87647049,  0.26600532,  1.2257925 ],
       [-0.26391087,  1.63878977,  0.55897257]])

In [25]:
arr.sort(0)

In [26]:
arr

array([[-0.87647049, -0.92214898, -0.8218954 ],
       [-0.26391087,  0.26600532, -0.66128384],
       [ 0.29463868,  0.27366227, -0.01064161],
       [ 0.3106557 ,  0.6784504 ,  0.55897257],
       [ 0.91224702,  1.63878977,  1.2257925 ]])

In [22]:
arr.sort(1)

In [23]:
arr

array([[-1.85608308, -1.36549328, -1.1381171 ],
       [-0.75923144, -0.26644469, -0.24324544],
       [-0.58434102, -0.25306099, -0.13531312],
       [ 0.17991356,  0.4760847 ,  0.81151403],
       [ 0.53164847,  0.9069392 ,  2.1349857 ]])

## Pandas Basic

In [27]:
frame = pd.DataFrame(np.arange(9).reshape(3,-1), index = ['a','c','d'],\
                    columns=['OH', 'TX', 'Cal'])

In [28]:
frame

OH  TX  Cal
a   0   1    2
c   3   4    5
d   6   7    8

In [29]:
frame.reindex(['a','b','c','d'])

OH   TX  Cal
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [30]:
frame.loc[['a','b','c'], ['OH','nan','TX']]

C:\Users\KTH\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


OH  nan   TX
a  0.0  NaN  1.0
b  NaN  NaN  NaN
c  3.0  NaN  4.0

In [31]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['U','O','T','Or'])

In [32]:
frame

b         d         e
U   0.090721  1.662827  0.415169
O  -1.533663  0.772339  1.480585
T  -0.218803  0.341488  0.082808
Or -0.045007  1.005499  0.458414

In [35]:
frame.apply(lambda x: x.max()-x.min(), axis=0) # axis=0 : row를 따라 : 1개 col을 넣어줌

b    1.624384
d    1.321339
e    1.397776
dtype: float64

In [38]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [40]:
frame.apply(f, axis=1)

min       max
U   0.090721  1.662827
O  -1.533663  1.480585
T  -0.218803  0.341488
Or -0.045007  1.005499

In [41]:
frame.apply(f, axis=0)

b         d         e
min -1.533663  0.341488  0.082808
max  0.090721  1.662827  1.480585

In [60]:
frame.applymap(lambda x: float('{0:.2f}'.format(x)))

b     d     e
U   0.09  1.66  0.42
O  -1.53  0.77  1.48
T  -0.22  0.34  0.08
Or -0.05  1.01  0.46

In [61]:
ser = pd.Series([2,3,1,2,4,1,2])
ser.rank()

0    4.0
1    6.0
2    1.5
3    4.0
4    7.0
5    1.5
6    4.0
dtype: float64

In [62]:
ser.rank(method='first')

0    3.0
1    6.0
2    1.0
3    4.0
4    7.0
5    2.0
6    5.0
dtype: float64

In [63]:
ser.rank(method='max')

0    5.0
1    6.0
2    2.0
3    5.0
4    7.0
5    2.0
6    5.0
dtype: float64

In [64]:
ser.rank(method='min')

0    3.0
1    6.0
2    1.0
3    3.0
4    7.0
5    1.0
6    3.0
dtype: float64

In [65]:
frame.count()

b    4
d    4
e    4
dtype: int64

In [66]:
frame

b         d         e
U   0.090721  1.662827  0.415169
O  -1.533663  0.772339  1.480585
T  -0.218803  0.341488  0.082808
Or -0.045007  1.005499  0.458414

In [67]:
frame.mean()

b   -0.426688
d    0.945538
e    0.609244
dtype: float64

In [68]:
frame.mean(axis=1)

U     0.722906
O     0.239754
T     0.068498
Or    0.472969
dtype: float64

## Series

In [2]:
obj = pd.Series(['c','a','d','a','a','b','c','c'])

In [3]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [4]:
obj.value_counts()

c    3
a    3
d    1
b    1
dtype: int64

In [7]:
pd.value_counts(obj.values, sort=True)

c    3
a    3
d    1
b    1
dtype: int64

In [8]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
dtype: bool

In [9]:
obj[mask]

0    c
5    b
6    c
7    c
dtype: object

In [10]:
data = pd.DataFrame({'Qu1': [1,3,4,2,1],
                     'Qu2': [1,3,1,2,3],
                     'Qu3': [1,5,2,4,4]})

In [11]:
data

Qu1  Qu2  Qu3
0    1    1    1
1    3    3    5
2    4    1    2
3    2    2    4
4    1    3    4

In [14]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  0.0
4  1.0  0.0  2.0
5  0.0  0.0  1.0

In [18]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  NaN
4  1.0  NaN  2.0
5  NaN  NaN  1.0

In [19]:
data.columns=['a','b','c']

In [20]:
data

a  b  c
0  1  1  1
1  3  3  5
2  4  1  2
3  2  2  4
4  1  3  4

In [22]:
data.apply(lambda x: x['a'] - x['c'] ,axis=1) 
# 아하 이런식으로 여러개 컬럼을 한꺼번에 사용가능!

0    0
1   -2
2    2
3   -2
4   -3
dtype: int64

In [24]:
data.apply(lambda x: x.mean()) # axis=0이면 row들을 합침

a    2.2
b    2.0
c    3.2
dtype: float64

In [25]:
data.applymap(lambda x : x-10)

a  b  c
0 -9 -9 -9
1 -7 -7 -5
2 -6 -9 -8
3 -8 -8 -6
4 -9 -7 -6

In [34]:
def makeprop(dat):
    dat['new'] = dat['b'] / dat['b'].sum()
    return dat

In [35]:
data.apply(makeprop, axis=1)

a    b    c  new
0  1.0  1.0  1.0  1.0
1  3.0  3.0  5.0  1.0
2  4.0  1.0  2.0  1.0
3  2.0  2.0  4.0  1.0
4  1.0  3.0  4.0  1.0

In [36]:
data.groupby('b').apply(makeprop)

a  b  c  new
0  1  1  1  0.5
1  3  3  5  0.5
2  4  1  2  0.5
3  2  2  4  1.0
4  1  3  4  0.5

In [39]:
data.name = 'idx'

In [40]:
data.name

'idx'

In [41]:
data

a  b  c
0  1  1  1
1  3  3  5
2  4  1  2
3  2  2  4
4  1  3  4

In [42]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [44]:
data.apply(lambda x :x.name +1, axis=1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
data.index.name

In [48]:
data.apply(pd.value_counts).fillna(0)

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  0.0
4  1.0  0.0  2.0
5  0.0  0.0  1.0

In [50]:
data.apply(pd.value_counts, axis=1)

1    2    3    4    5
0  3.0  NaN  NaN  NaN  NaN
1  NaN  NaN  2.0  NaN  1.0
2  1.0  1.0  NaN  1.0  NaN
3  NaN  2.0  NaN  1.0  NaN
4  1.0  NaN  1.0  1.0  NaN

In [51]:
data

a  b  c
0  1  1  1
1  3  3  5
2  4  1  2
3  2  2  4
4  1  3  4

In [107]:
df = data.apply(pd.value_counts)

In [108]:
df.loc[5,'c'] = np.nan
df

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  NaN
4  1.0  NaN  2.0
5  NaN  NaN  NaN

In [109]:
df.dropna(how='any')

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0

In [110]:
df.dropna(how='all')

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  NaN
4  1.0  NaN  2.0

In [111]:
df.dropna(thresh=2)

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  NaN
4  1.0  NaN  2.0

In [112]:
df.fillna({'a':df['a'].mean(), 'b':0, 'c':0.25})

a    b     c
1  2.00  2.0  1.00
2  1.00  1.0  1.00
3  1.00  2.0  0.25
4  1.00  0.0  2.00
5  1.25  0.0  0.25

In [113]:
df

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  NaN
4  1.0  NaN  2.0
5  NaN  NaN  NaN

In [114]:
df.fillna(method='ffill')

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  1.0
4  1.0  2.0  2.0
5  1.0  2.0  2.0

In [115]:
df.fillna(method='bfill')

a    b    c
1  2.0  2.0  1.0
2  1.0  1.0  1.0
3  1.0  2.0  2.0
4  1.0  NaN  2.0
5  NaN  NaN  NaN

In [116]:
df.index.names = ['key1']

In [117]:
df

a    b    c
key1               
1     2.0  2.0  1.0
2     1.0  1.0  1.0
3     1.0  2.0  NaN
4     1.0  NaN  2.0
5     NaN  NaN  NaN

In [118]:
df.index = pd.MultiIndex.from_arrays([['ap','ap','bp','bp','bp'],['1','2','1','2','3']],\
                                    names=['key1','key2'])

In [119]:
df

a    b    c
key1 key2               
ap   1     2.0  2.0  1.0
     2     1.0  1.0  1.0
bp   1     1.0  2.0  NaN
     2     1.0  NaN  2.0
     3     NaN  NaN  NaN

In [120]:
df.unstack()

a             b             c         
key2    1    2   3    1    2   3    1    2   3
key1                                          
ap    2.0  1.0 NaN  2.0  1.0 NaN  1.0  1.0 NaN
bp    1.0  1.0 NaN  2.0  NaN NaN  NaN  2.0 NaN

In [121]:
df

a    b    c
key1 key2               
ap   1     2.0  2.0  1.0
     2     1.0  1.0  1.0
bp   1     1.0  2.0  NaN
     2     1.0  NaN  2.0
     3     NaN  NaN  NaN

In [122]:
df['a']

key1  key2
ap    1       2.0
      2       1.0
bp    1       1.0
      2       1.0
      3       NaN
Name: a, dtype: float64

In [123]:
df.a.unstack()

key2    1    2   3
key1              
ap    2.0  1.0 NaN
bp    1.0  1.0 NaN

In [124]:
df.swaplevel('key1','key2')

a    b    c
key2 key1               
1    ap    2.0  2.0  1.0
2    ap    1.0  1.0  1.0
1    bp    1.0  2.0  NaN
2    bp    1.0  NaN  2.0
3    bp    NaN  NaN  NaN

In [125]:
df.swaplevel('key1','key2').sort_values(by='key2')

a    b    c
key2 key1               
1    ap    2.0  2.0  1.0
     bp    1.0  2.0  NaN
2    ap    1.0  1.0  1.0
     bp    1.0  NaN  2.0
3    bp    NaN  NaN  NaN

In [126]:
df.swaplevel('key1','key2').sort_values(by='key2').reset_index()

key2 key1    a    b    c
0    1   ap  2.0  2.0  1.0
1    1   bp  1.0  2.0  NaN
2    2   ap  1.0  1.0  1.0
3    2   bp  1.0  NaN  2.0
4    3   bp  NaN  NaN  NaN

In [127]:
df

a    b    c
key1 key2               
ap   1     2.0  2.0  1.0
     2     1.0  1.0  1.0
bp   1     1.0  2.0  NaN
     2     1.0  NaN  2.0
     3     NaN  NaN  NaN

In [128]:
df.sum(level='key1') #groupby처럼 쓸 수 있음

a    b    c
key1               
ap    3.0  3.0  2.0
bp    2.0  2.0  2.0

In [129]:
df.groupby('key1').sum()

a    b    c
key1               
ap    3.0  3.0  2.0
bp    2.0  2.0  2.0

In [130]:
df

a    b    c
key1 key2               
ap   1     2.0  2.0  1.0
     2     1.0  1.0  1.0
bp   1     1.0  2.0  NaN
     2     1.0  NaN  2.0
     3     NaN  NaN  NaN

In [131]:
df = df.reset_index()
df

key1 key2    a    b    c
0   ap    1  2.0  2.0  1.0
1   ap    2  1.0  1.0  1.0
2   bp    1  1.0  2.0  NaN
3   bp    2  1.0  NaN  2.0
4   bp    3  NaN  NaN  NaN

In [132]:
df = df.fillna(0).set_index(['a','c'])

In [133]:
df

key1 key2    b
a   c                 
2.0 1.0   ap    1  2.0
1.0 1.0   ap    2  1.0
    0.0   bp    1  2.0
    2.0   bp    2  0.0
0.0 0.0   bp    3  0.0

In [135]:
df.sort_values('a', ascending=True)

key1 key2    b
a   c                 
0.0 0.0   bp    3  0.0
1.0 1.0   ap    2  1.0
    0.0   bp    1  2.0
    2.0   bp    2  0.0
2.0 1.0   ap    1  2.0

### Merge

In [140]:
df1 = pd.DataFrame({'key' : ['b','b','a','c','a','b'],
                    'data1' : range(6)})
df2 = pd.DataFrame({'key' : ['a','b','a','b','d'],
                    'data2' : range(5)})

In [141]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [142]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [143]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [149]:
df_t = pd.merge(df1,df2,on='key',how='left').sort_values(by='key').reset_index(drop=True)
df_t

key  data1  data2
0    a      2    0.0
1    a      2    2.0
2    a      4    0.0
3    a      4    2.0
4    b      0    1.0
5    b      0    3.0
6    b      1    1.0
7    b      1    3.0
8    b      5    1.0
9    b      5    3.0
10   c      3    NaN

In [153]:
# 만약 그냥 딱 왼쪽놈만 합치고프면 : 이거 좀 비효율적이지 않나?
df_t.pivot_table('data1',index='key',columns='data2',aggfunc='mean')

data2  0.0  1.0  2.0  3.0
key                      
a      3.0  NaN  3.0  NaN
b      NaN  2.0  NaN  2.0

In [154]:
pd.merge(df1,df2,on='key',how='inner') # 둘이 공통으로 가진 값들의 데카르트 곱 반환

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [162]:
df_1 = pd.DataFrame(np.arange(20).reshape(10,-1), columns=['a','b'])
df_1['a'] = range(10)
df_1

a   b
0  0   1
1  1   3
2  2   5
3  3   7
4  4   9
5  5  11
6  6  13
7  7  15
8  8  17
9  9  19

In [163]:
df_2 = pd.DataFrame({'a':np.arange(10),'b':np.arange(40,60,2)})
df_2

a   b
0  0  40
1  1  42
2  2  44
3  3  46
4  4  48
5  5  50
6  6  52
7  7  54
8  8  56
9  9  58

In [165]:
pd.merge(df_1,df_2, on='a') # 만약 key가 중복이 없으면 그대로 나오징! join대로!

a  b_x  b_y
0  0    1   40
1  1    3   42
2  2    5   44
3  3    7   46
4  4    9   48
5  5   11   50
6  6   13   52
7  7   15   54
8  8   17   56
9  9   19   58